import { defineConfig } from "cz-git";

export default defineConfig({
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "docs",
        "style",
        "refactor",
        "test",
        "build",
        "ci",
        "config",
        "tool",
        "infra",
        "revert",
      ],
    ],
  },
  prompt: {
    alias: {
      fd: "docs: タイポ修正",
    },
    messages: {
      type: "コミットの種類を選択してください:",
      scope: "変更のスコープを指定してください（任意）: ",
      customScope: "変更のスコープを指定してください:",
      subject: "変更の短い、命令形の説明を入力してください:\n",
      body: '変更の詳細な説明を入力してください（任意）。新しい行を作る場合は"|"\nを使用:\n',
      breaking:
        'BREAKING CHANGESを列挙してください（任意）。新しい行を作る場合は"|"\nを使用:\n',
      footerPrefixesSelect:
        "変更に関連するISSUESの種類を選択してください（任意）: ",
      customFooterPrefix: "カスタムISSUESプレフィックスを入力:",
      footer: "この変更に関連するISSUESを列挙してください。例： #31, #34:\n",
      generatingByAI: "コミットメッセージを生成中...",
      generatedSelectByAI: "適切なサブジェクトをAIが生成したものから選択:",
      confirmCommit: "上記のコミット内容で進めていいですか？",
    },
    types: [
      { value: "feat", name: "feat:     ✨  新機能の追加", emoji: "✨" },
      { value: "fix", name: "fix:      🐛  バグ修正", emoji: "🐛" },
      {
        value: "docs",
        name: "docs:     📝  ドキュメント整備（README やテンプレートなど）",
        emoji: "📝",
      },
      {
        value: "style",
        name: "style:    💄  コード整形・エディタ設定など（意味に影響なし）",
        emoji: "💄",
      },
      {
        value: "refactor",
        name: "refactor: ♻️   機能追加・バグ修正を含まないリファクタリング",
        emoji: "♻️",
      },
      {
        value: "test",
        name: "test:     ✅  テスト追加や修正（unit, integration, bats等）",
        emoji: "✅",
      },
      {
        value: "build",
        name: "build:    📦️  ビルド設定や依存パッケージ関連の変更",
        emoji: "📦️",
      },
      {
        value: "ci",
        name: "ci:       🎡  GitHub Actions 等 CI構成",
        emoji: "🎡",
      },
      {
        value: "config",
        name: "config:   ⚙️   commitlint, ruff, editorconfig などの設定変更",
        emoji: "⚙️",
      },
      {
        value: "tool",
        name: "tool:     🛠  補助スクリプトや開発ツールの追加・整備",
        emoji: "🛠",
      },
      {
        value: "infra",
        name: "infra:    🧱  GitHub Projects や環境構築スクリプト関連",
        emoji: "🧱",
      },
      {
        value: "revert",
        name: "revert:   ⏪️  過去のコミットの取り消し",
        emoji: "⏪️",
      },
    ],
    useEmoji: true,
    emojiAlign: "center",
    useAI: true,
    aiNumber: 1,
    themeColorCode: "",
    scopes: [],
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlign: "bottom",
    customScopesAlias: "custom",
    emptyScopesAlias: "empty",
    upperCaseSubject: false,
    markBreakingChangeMode: false,
    allowBreakingChanges: ["feat", "fix"],
    breaklineNumber: 100,
    breaklineChar: "|",
    skipQuestions: [],
    issuePrefixes: [{ value: "closed", name: "closed:   処理済みISSUES" }],
    customIssuePrefixAlign: "top",
    emptyIssuePrefixAlias: "skip",
    customIssuePrefixAlias: "custom",
    allowCustomIssuePrefix: true,
    allowEmptyIssuePrefix: true,
    confirmColorize: true,
    scopeOverrides: undefined,
    defaultBody: "",
    defaultIssues: "",
    defaultScope: "",
    defaultSubject: "",
  },
});
