[project]
dependencies = [
    "pydantic>=2.11.3",
]
description = "apt package migration to brew(linux) package manager"
name = "package-migration-tools"
readme = "README.md"
requires-python = ">=3.13"
version = "0.1.0"

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
    "pytest-cov>=6.0.0",
    "ruff>=0.11.2",
]
