blank_issues_enabled: false
contact_links: []

issue_templates:
  - name: 🛠 Task Template
    description: 実装・整備タスクなどの進行管理に使用するテンプレートです。
    file: task_template.md
#  - name: 🐛 Bug Report
#    description: 不具合・バグの報告はこちらから。
#    file: bug_report.md
#  - name: ✨ Feature Request
#    description: 新機能の提案や改善アイデアはこちらから。
#    file: feature_request.md
